FOUNDATIONS: Retrieve All ShoppingItems
Mums-Who-Code/ShoppingList pull request #16
Opened 2022-05-06 04:08 UTC by tharanisantosh

2022-05-06 16:26 UTC, ShriHumrudha requested changes

2022-05-06 16:26 UTC, ShriHumrudha commented on ShoppingList.Tests.Unit/Services/Foundations/ShoppingItems/ShoppingItemServiceTests.Exceptions.RetrieveAll.cs
> +            // when
New line break required

2022-05-06 16:26 UTC, ShriHumrudha commented on ShoppingList.ConsoleApp/Services/Foundations/ShoppingItems/ShoppingItemService.cs
> +           return this.storageBroker.SelectAllShoppingItems();
Correct the tab alignment here

2022-05-06 16:26 UTC, ShriHumrudha commented on ShoppingList.Tests.Unit/Services/Foundations/ShoppingItems/ShoppingItemServiceTests.cs
> +        private static List<ShoppingItem> CreateRandomShoppingItems() =>
Need new line break

2022-05-07 01:33 UTC, tharanisantosh commented on ShoppingList.Tests.Unit/Services/Foundations/ShoppingItems/ShoppingItemServiceTests.Exceptions.RetrieveAll.cs
> +            // when
Comment Resolved.

2022-05-07 01:34 UTC, tharanisantosh commented on ShoppingList.ConsoleApp/Services/Foundations/ShoppingItems/ShoppingItemService.cs
> +           return this.storageBroker.SelectAllShoppingItems();
Comment Resolved.

2022-05-07 01:37 UTC, tharanisantosh commented on ShoppingList.Tests.Unit/Services/Foundations/ShoppingItems/ShoppingItemServiceTests.cs
> +        private static List<ShoppingItem> CreateRandomShoppingItems() =>
Comment Resolved.

2022-05-07 01:41 UTC, ShriHumrudha approved these changes

2022-05-07 01:41 UTC, merged