BROKER: Insert Shopping
Mums-Who-Code/ShoppingList pull request #4
Opened 2021-11-30 16:32 UTC by tharanisantosh

2021-11-30 19:33 UTC, ShriHumrudha requested changes

2021-11-30 19:33 UTC, ShriHumrudha commented on ShoppingList.ConsoleApp/Models/Shopping/Shopping.cs
> +        public string Text { get; set; }
You need to choose the attributes for your model that are relevant for your model - ShoppingList.

2021-11-30 19:33 UTC, ShriHumrudha commented on ShoppingList.ConsoleApp/Models/Shopping/Shopping.cs
> +    class Shopping
Your model name should be a noun. may be 'Item'?

2021-11-30 19:33 UTC, ShriHumrudha commented on ShoppingList.ConsoleApp/Brokers/Storages/IStorageBroker.ShoppingItem.cs
> +using ShoppingList.ConsoleApp.Models.ShoppingItems;
Need a new line space between the comments and using statement

2021-11-30 19:33 UTC, ShriHumrudha commented on ShoppingList.ConsoleApp/Models/ShoppingItems/ShoppingItem.cs
> +        public string Text { get; set; }
Name would be a more appropriate variable name.
Also just have 3 maximum. We will add more attributed later. So Id + 2 more.

2021-11-30 19:33 UTC, ShriHumrudha commented on ShoppingList.ConsoleApp/Brokers/Storages/StorageBroker.ShoppingItem.cs
> +        List<ShoppingItem> ShoppingItems = new List<ShoppingItem>();
You need to have a namespace here.

2021-12-01 02:59 UTC, tharanisantosh commented on ShoppingList.ConsoleApp/Models/Shopping/Shopping.cs
> +        public string Text { get; set; }
Resolved all the comments.

2021-12-01 03:01 UTC, ShriHumrudha approved these changes

2021-12-01 03:01 UTC, merged